require File.expand_path('../votifier/vote', __FILE__)
require File.expand_path('../votifier/server', __FILE__)
require File.expand_path('../votifier/client', __FILE__)
require File.expand_path('../votifier/key', __FILE__)
require File.expand_path('../votifier/minecraft_server', __FILE__)
